In [1]:
import numpy as np
import pandas as pd

Pivot Tables

In [3]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100,1000,20),
    'Units': np.random.randint(10,100,20),
    'Rep': ['John', 'Hary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)

In [4]:
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    551     32   John  January      Q1
1  2023-01-02       B   West    751     60   Hary  January      Q1
2  2023-01-03       C  North    151     23    Bob  January      Q1
3  2023-01-04       D  South    815     85  Alice  January      Q1
4  2023-01-05       A   East    122     77   John  January      Q1
5  2023-01-06       B   West    256     43   Mary  January      Q1
6  2023-01-07       C  North    884     93    Bob  January      Q1
7  2023-01-08       D  South    542     35  Alice  January      Q1
8  2023-01-09       A   East    553     68   John  January      Q1
9  2023-01-10       B   West    633     60   Mary  January      Q1
10 2023-01-11       C  North    873     80    Bob  January      Q1
11 2023-01-12       D  South    704     62  Alice  January      Q1
12 2023-01-13       A   East    256     72   John  January      Q1
13 2023-01-14       B   West    270     47   Mary  January      Q1
14 2023-01-15       C  North    380     93    Bob  January      Q1
15 2023-01-16       D  South    371     99  Alice  January      Q1
16 2023-01-17       A   East    683     51   John  January      Q1
17 2023-01-18       B   West    774     64   Mary  January      Q1
18 2023-01-19       C  North    387     52    Bob  January      Q1
19 2023-01-20       D  South    645     74  Alice  January      Q1

In [7]:
pd.pivot_table(df, values="Sales", index="Region", columns="Product", aggfunc='median')

Product      A      B      C      D
Region
East     551.0    NaN    NaN    NaN
North      NaN    NaN  387.0    NaN
South      NaN    NaN    NaN  645.0
West       NaN  633.0    NaN    NaN

In [8]:
pivot2 = pd.pivot_table(df, values=['Sales', 'Units'], index = 'Region', columns='Product')

In [9]:
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     433.0    NaN    NaN    NaN  60.0   NaN   NaN   NaN
North      NaN    NaN  535.0    NaN   NaN   NaN  68.2   NaN
South      NaN    NaN    NaN  615.4   NaN   NaN   NaN  71.0
West       NaN  536.8    NaN    NaN   NaN  54.8   NaN   NaN

In [10]:
pd.crosstab(df['Region'], df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0